#define MEM_SIZE 4096
#define GPR_COUNT 16
#define STACK_SIZE 16

#define INSTR_SIZE_B 2

#define INTERPRETER_START_ADDR 0x000
#define INTERPRETER_END_ADDR 0x1ff
#define PROGRAM_START_ADDR 0x200
#define PROGRAM_END_ADDR 0xe8f
#define RESERVED_START_ADDR 0xea0
#define RESERVED_END_ADDR 0xfff

#define DIGIT_SPRITES_START_ADDR 0x050
#define DIGIT_SPRITES_END_ADDR 0x09f

#define DISPLAY_WIDTH 64
#define DISPLAY_HEIGHT 32
#define DISPLAY_REFRESH_RATE 60

#define DISPLAY_WHITE 0x1
#define DISPLAY_BLACK 0x0

#define SPRITE_MAX_WIDTH 8
#define SPRITE_MAX_HEIGHT 16
#define FONT_WIDTH 4
#define FONT_HEIGHT 5

#define DELAY_TIMER_DECREMENT_RATE 60